name: Test IPFS connection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name (one of: dev-unstable, testnet-clay, mainnet)'
        required: true
        default: 'dev-unstable'

# TODO: Make this smarter so it only runs for environment that actually gets updated
jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - env: dev-unstable
          - env: testnet-clay
          - env: mainnet
    env:
      JEST_CERAMIC_NETWORK: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run test
        run: |
            cd ./test
            npm ci
            npm run test
