name: Test IPFS connection

on:
  push:
    branches:
      - main
    paths: "*.json"
  pull_request:
    branches:
      - main
    paths: "*.json"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name (one of: dev-unstable, testnet-clay, mainnet)'
        required: true
        default: 'dev-unstable'

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - env: dev-unstable
          - env: testnet-clay
          - env: mainnet
    env:
      JEST_CERAMIC_NETWORK: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: List changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.5
        with:
          files: |
            dev-unstable.json
            testnet-clay.json
            mainnet.json
      - name: Run test
        if: contains(steps.changed-files.outputs.modified_files, "${{ matrix.env }}.json")
        run: |
            cd ./test
            npm ci
            npm run test
